name: Delivery
on:
  push:
    branches:
      - main

jobs:
  delivery:
    name: Delivery
    runs-on: ubuntu-24.04
    environment: Production
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: "pnpm"

      - name: Make project
        run: make

      - name: Create tag, bump version and generate Changelogs
        id: conventional
        uses: TriPSs/conventional-changelog-action@v5
        with:
          github-token: ${{ secrets.github_token }}
          skip-git-pull: true
          config-file-path: "./conventional-changelog-action.config.js"

      - name: Build project
        env:
          VERSION: ${{ steps.conventional.outputs.tag }}
        run: pnpm build

      - name: Archive dist
        run: tar -czf dist.tar.gz dist

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.conventional.outputs.changelog }}
          tag_name: ${{ steps.conventional.outputs.tag }}
          name: ${{ steps.conventional.outputs.tag }}
          files: |
            dist.tar.gz

      - name: Deploy to CF pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=amendoadev
